version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: ai-validator-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mongo
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ai_db
      MONGO_URL: mongodb://mongo:27017/pdfstore
    volumes:
      - ./apps/api:/app
    restart: always

  document-api:
    build:
      context: ./apps/document-api
      dockerfile: Dockerfile
    container_name: ai-validator-document-api
    ports:
      - "3001:3000"
    depends_on:
      - db
      - mongo
    environment:
      DATABASE_URL: postgres://user:pass@db:5432/ai_db
      MONGO_URL: mongodb://mongo:27017/pdfstore
    volumes:
      - ./apps/document-api:/app
    restart: always

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: ai-validator-web
    ports:
      - "3002:3000"
    volumes:
      - ./apps/web:/app
    restart: always

  db:
    image: postgres:14
    container_name: ai-validator-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ai_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  mongo:
    image: mongo
    container_name: ai-validator-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  db-data:
  mongo-data:
